### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory in 1.16.5

### ISSUE THREAD

**Issue by zaoe** [Nova-Committee/MomLove#5]
Mod File: MomLove-Forge-1.16.5-1.1.0.jar
	Failure message: MomLove (momlove) has failed to load correctly
		java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	Mod Version: 1.1.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory

**Comment by cnlimiter** [comment]
> Mod File: MomLove-Forge-1.16.5-1.1.0.jar Failure message: MomLove (momlove) has failed to load correctly java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory Mod Version: 1.1.0 Mod Issue URL: NOT PROVIDED Exception message: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory

see curseforge
